name = "Jörmungandr"
license = "MIT"
licenselink = "https://github.com/daveagill/jormungandr/blob/master/LICENSE.md"
description = "Jörmungandr is a minimalist, responsive Hugo theme."
homepage = "https://github.com/daveagill/jormungandr"
tags = ["minimalist", "clean", "responsive", "typography"]
features = ["flexible", "fast", "highlight.js", "thumbnails", "internationalization"]
min_version = 0.43

[author]
  name = "David Gill"
  homepage = "http://gilldave.co.uk"

[original]
    name = "Gökmen Görgen"
    homepage = "https://gokmengorgen.net"
    repo = "https://github.com/gkmngrgn/hugo-alageek-theme"