title = "Jörmungandr Theme"

author = "Your Name"
copyright = "Copyright © Your Name; all rights reserved."

theme = "jormungandr"


[params]
    copyright = "© Your Name"
    copyrightUrl = "https://themes.gohugo.io/theme/jormungandr/"
    faviconfile = "img/favicon.ico"
    logofile = "img/logo.jpg"
    logoAsCircle = true
    latestpostcount = 5
    github = "daveagill/jormungandr"
    
    highlightjs = true
    posts_navigation = true

    [params.taxonomies]
        showOnBlogSection = true
        minUsage = 0

[[params.best_posts]]
    title = "Migrate to Hugo from Jekyll"
    url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.primary]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20