title = "Jörmungandr Theme"

author = "Your Name"
copyright = "Copyright © Your Name; all rights reserved."

theme = "jormungandr"


[params]
    copyright = "© Your Name"
    copyrightUrl = "https://themes.gohugo.io/theme/jormungandr/"
    faviconfile = "img/favicon.ico"
    logofile = "img/logo.jpg"
    logoAsCircle = true

    highlightjs = true

    [[params.social]]
        name = "GitHub"
        url = "https://github.com/daveagill/jormungandr"
        icon = "fab fa-github"
        color = "#000000"

    [[params.social]]
        name = "RSS Feed"
        url = "/index.xml"
        icon = "fas fa-rss"
        color = "#ee802f"

    [params.taxonomies]
        showOnBlogSection = true
        minUsage = 0

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20