baseURL = "https://example.com"
languageCode = "en"

title = "Jörmungandr Theme"
copyright = "Copyright © {year} Your Name; all rights reserved."

theme = "jormungandr"
preserveTaxonomyNames = true

disqusShortname = "enter-your-discuss-shortname"

[params]
    author = "Your Name"
    description = "A description about your blog or website."
    
    logo = "/logo.jpg"
    logoAsCircle = true

    highlightjs = true

    [params.taxonomies]
        showOnBlogSection = true
        minUsage = 0

    [[params.social]]
        name = "GitHub"
        url = "https://github.com"
        icon = "fab fa-github"
        color = "#000000"

    [[params.social]]
        name = "Twitter"
        url = "https://twitter.com"
        icon = "fab fa-twitter"
        color = "#1da1f2"

    [[params.social]]
        name = "LinkedIn"
        url = "https://linkedin.com/"
        icon = "fab fa-linkedin"
        color = "#007bb5"

    [[params.social]]
        name = "YouTube"
        url = "https://youtube.com"
        icon = "fab fa-youtube"
        color = "#ff0000"

    [[params.social]]
        name = "RSS Feed"
        url = "/index.xml"
        icon = "fas fa-rss"
        color = "#ee802f"

[[menu.main]]
    pre = "↪ "
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.main]]
    pre = "↪ "
    name = "About The Theme"
    url = "/about/"
    weight = 20