title = "Jörmungandr Theme"

author = "Your Name"
copyright = "Copyright © Your Name; all rights reserved."

theme = "jormungandr"


[params]
    copyright = "© Your Name"
    copyrightUrl = "https://themes.gohugo.io/theme/jormungandr/"
    faviconfile = "img/favicon.ico"
    logofile = "img/logo.jpg"
    logoAsCircle = true

    highlightjs = true
    posts_navigation = true

    [params.social]
        github = "daveagill/jormungandr"

    [params.taxonomies]
        showOnBlogSection = true
        minUsage = 0

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20